### ISSUE TITLE
Error accessing "Call Reports" -> "DNID"

### ISSUE THREAD

**Issue by JoseGoncalves** [radiusone/a2billing#10]
On accesses to "Call Reports" -> "DNID" a fatal error is happening:
> PHP Fatal error:  Uncaught Error: Undefined constant "download" in /var/www/html/a2billing/admin/Public/call-dnid.php:47

**Comment by miken32** [comment]
So about 15 years ago they decided to move to a slightly better model for their code; rather than using the same boilerplate code for every page they centralized stuff in what is now at `templates/ViewHandler.php` and `src/Forms/FormHandler.php`. It's certainly not great but it's better than what it was.

For some reason there's a dozen or so pages they didn't change over to use the FormHandler functions, and this is one of them. Any page that doesn't start with `A2B_` is going to be *the worst*. See commit 0950410e for an example of what was done with `admin/Public/call-log-customers.php` to get it in line with the other pages I updated.

All that to say: I put some quotes in that file to fix this problem, but until (or if) I update it fully, don't expect it to work well, don't expect it to look good, and don't be surprised if other errors pop up.
